### ISSUE TITLE
CITY_REQUIRED err but values

### ISSUE THREAD

**Issue by solidevolution** [maxmind/ccfd-api-php#17]
To get informations about the geolocation and the proxy score, we use this library.

If we transmit license, ip and city it works but without city we get his error. Why?

**Comment by solidevolution** [comment]
With

$this->bSkipOnError = false;

it works but is there a possibility to skip warnings but not skipping errors?

$this->bSkipOnError = true;

takes the warnings as errors ...

**Comment by oschwald** [comment]
I am a bit confused. As far as I know, this API doesn't have a `bSkipOnError` property. Are you sure this isn't coming from your own code?

The service may returning warnings in the `err` field.

**Comment by solidevolution** [comment]
You're right, sorry. bSkipOnError comes from our code which runs in errors in cause of warnings in the err field. Its in the documentation but an error means for me, i've got no values but from MaxMind we got values for lng/lat and an error ... disgusting

**Comment by oschwald** [comment]
If you are not seeing a IP lat/long on a request with an IP address but no country, please contact support@maxmind.com with the details about the request. It is outside the scope of this particular API.

The [minFraud documentation](http://dev.maxmind.com/minfraud/#Error_Reporting) lists which errors are true errors and which are warnings.
