### ISSUE TITLE
Typos/Bugs in scripts

### ISSUE THREAD

**Issue by nimasdj** [maxmind/ccfd-api-php#18]
1) I found a bug in src/TelephoneVerification.php
```php
$this->url = "app/telephone_http";
```
is an invalid url and causes "Not found" error.
this url must be changed to:
```php
$this->url = "app/phone_id_http";
```
as stated here:
https://www.maxmind.com/en/implementation-guidelines-for-telephone-number-identification
and that will work fine.

2) $isSecure is set in HTTBase.php to false as default and you should not set them true in src/TelephoneVerification.php nor in src/CreditCardFraudDetection.php, but end-user should set it to true in /examples/*.php

3) in examples/telephone-verification.php:
```php
$ccfs->wsIpaddrRefreshTimeout = 3600 * 5;
$ccfs->wsIpaddrCacheFile = "/tmp/maxmind.ws.cache";
$ccfs->useDNS = false;
```
must be removed. There is no $ccfs instance in this script, nor there are such properties in HTTBase.php to be set, and I guess these properties will be ignored in __set method because of property_exists() checking.

**Comment by nimasdj** [comment]
4) sessionID removed from minfraud.php example as it is deprecated but the property kept as a valid property in HTTPBase.php for backward compatibility.

**Comment by oschwald** [comment]
Hello, thanks for the PR. The API is in a bit of a state of disrepair, but the issues are a bit different than described. Addressing your points:

1. The telephone verification service has been discontinued. As you noticed, we also have a phone ID service, but the API was not designed to use it. Changing it in the manner you describe might work, but I don't think we want to support that generally, and certainly not with the TelephoneVerification class, which was for another service.
2. We want HTTPS on by default for these services. Perhaps the examples should be updated.
3. The example should be removed along with the class.

**Comment by nimasdj** [comment]
As about #2 I think it should be set to true in HTTBase and not in CreditCard... nor in PhonwVeri....

**Comment by oschwald** [comment]
I'm not sure why it was changed in the subclasses originally. Perhaps to selectively enable HTTPS.

**Comment by nimasdj** [comment]
if 'selectively' then it should enabled in examples and not in subclasses!

**Comment by nimasdj** [comment]
The best way, is set to true as default in HTTBase and remove from subclasses, then end-user can turn it off. I can add a method to HTTBase to determine whether ssl is installed on server, if yes turn on https, if no turn off, this way end-user doesn't need to be worry to set this property in examples at all, as it would be automatic. interested in this method that I add?

**Comment by oschwald** [comment]
By selectively, I meant we likely wanted it enabled for some web services but not others. As I mentioned, I am speculating. There is also the concern that someone else might be subclassing HTTPBase themselves and changing HTTPS to be default there may break their integration.

We want HTTPS to be on by default and to error if it is not available, assuming the user hasn't explicitly disabled it. We don't want to detect it and automatically disable it if not available, as the user may unknowingly send their data encrypted.

As I mentioned previously, the examples should be updated.

**Comment by nimasdj** [comment]
At meanwhile I did minor cleanup in examples/minfraud to get some values from $_SERVER instead of hardcoding in examples.

**Comment by oschwald** [comment]
I am closing this PR as we release 1.70 with the TVS class removed. Please feel free to create an small PR fro the examples changes though.

**Comment by nimasdj** [comment]
@oschwald
Ok, instead of TVS you could add class for Phone lookup service just by small modifications in TVS class.
