### ISSUE TITLE
psr-4 namespace instead of file for composer autoloader

### ISSUE THREAD

**Issue by nimasdj** [maxmind/ccfd-api-php#21]
You should consider to use psr-4 with namespace with composer instead of using "file" in composer.json. Because if using namespace, composer autoloader calls class only when needed but if using "file", composer autoloader calls classes immediately when autoload.php is required and this is bad for performance.

**Comment by oschwald** [comment]
Although I agree namespaces would be an improvement, it would involve an API change. This API is in maintenance-only mode. If you want a more modern API, please see our [minFraud beta API](https://github.com/maxmind/minfraud-api-php).

**Comment by nimasdj** [comment]
I don't understand what API change?! You just need to add a namespace to classes and edit composer.json. Do you want me to do a pull request?

**Comment by oschwald** [comment]
Adding a namespace to the classes is a breaking API change.

**Comment by nimasdj** [comment]
I don't think so. Anyway until mid 2016 Insight Beta will not be GA so still better to improve this. I can do pull request with well tested changes to make sure it works. Do you want me to pull request?

**Comment by oschwald** [comment]
How is this not a breaking API change? Anyone using the API would need to update their code to import the namespace. A PR for a breaking API change will not be accepted.

**Comment by nimasdj** [comment]
When you release it with a major version, his conposer.lock will not update to this version, anyone installing this major version will use the namespace as per new construction.

**Comment by oschwald** [comment]
As mentioned, this API is in maintenance mode. We aren't making breaking changes or releasing new major versions.

**Comment by nimasdj** [comment]
As long as this legacy API is not completely dead, and MaxMind supports it, you should not stop improving this code and release major versions. Your reason sounds very silly!
