### ISSUE TITLE
BIN name containing "&amp;" throws "Undefined offset" error

### ISSUE THREAD

**Issue by markwilson** [maxmind/ccfd-api-php#25]
When using the credit card fraud detection and passing a BIN of 551007 I get back this in the response string:-

```
...;ip_longitude=;binName=Enterprise Bank &amp; Trust;ip_isp=;...
```

The string gets split by ";" so this creates an invalid item in the array. This array is then further split by "=" but because the array value it is checking is " Trust" it will throw an error. Also, the `binName` is then incorrectly assigned as "Enterprise Bank &amp".

**Comment by oschwald** [comment]
Thanks for reporting this. We will be fixing this on the server side.

**Comment by oschwald** [comment]
This should be fixed now.

**Comment by markwilson** [comment]
Thanks for resolving so quickly 👍
